### ISSUE TITLE
Wrong project name in the oc get route 

### ISSUE THREAD

**Issue by vpagar1** [konveyor/mig-demo-apps#22]
Hello Pranav,

I can see in the manifest file the project name we are using is "mssql-persistent" and the one which you used in the oc get route is "mssql-example" so we might need to correct this. 

# oc get route -n mssql-example mssql-app-route -o go-template='{{ .spec.host }}{{ println }}'

**Comment by pranavgaikwad** [comment]
Closed thru #23
