### ISSUE TITLE
robot-shop application is not getting installed in openshift 4.4 cluster

### ISSUE THREAD

**Issue by ashoks27** [konveyor/mig-demo-apps#24]
HI All ,

I am trying to install robot-shop application in openshift 4.4 cluster ( It is working fine in 3.11 ) and the mysql-1-hook-post is not getting creating . Attached below the logs for the pods , pvc and sc. Please help here to fix the issue .

[root@oc4377604745 ~]# oc get pods
NAME                         READY   STATUS              RESTARTS   AGE
cart-699567cb75-55zq5        1/1     Running             0          11m
catalogue-7476fdc8f4-8z85p   1/1     Running             0          11m
dispatch-85ff479cdd-rgrjv    1/1     Running             0          11m
mongodb-59b795bd6b-nzxnq     1/1     Running             0          10m
mysql-1-68x64                2/2     Running             0          10m
mysql-1-deploy               1/1     Running             0          10m
**mysql-1-hook-post            0/1     ContainerCreating   0          8m9s**
payment-695779d6bb-c68lr     1/1     Running             0          10m
rabbitmq-7b44f9c449-rzlmg    1/1     Running             0          10m
ratings-c45895c99-qkblf      1/1     Running             0          10m
redis-78dd47d8c-2w59c        1/1     Running             0          10m
shipping-6fbbc47b67-gq5z8    1/1     Running             0          10m
user-56987c97fd-q498c        1/1     Running             0          10m
web-ffbbb68c7-v9jcz          1/1     Running             0          10m
[root@oc4377604745 ~]# 

Events:
  Type     Reason       Age                  From                    Message
  ----     ------       ----                 ----                    -------
  Normal   Scheduled    <unknown>            default-scheduler       Successfully assigned robot-shop/mysql-1-hook-post to 10.74.175.170
  Warning  FailedMount  21s                  kubelet, 10.74.175.170  Unable to attach or mount volumes: unmounted volumes=[mysql-scripts-volume], unattached volumes=[mysql-scripts-volume default-token-pfq9s]: timed out waiting for the condition
  Warning  FailedMount  10s (x9 over 2m23s)  kubelet, 10.74.175.170  MountVolume.SetUp failed for volume "pvc-7ef040e5-fc3d-41b3-97a7-19d593489eb6" : mount command failed, status: Failure, reason: Error while mounting the volume &errors.errorString{s:"RWO check has failed. DevicePath /var/lib/kubelet/plugins/kubernetes.io/flexvolume/ibm/ibmc-block/mounts/pvc-7ef040e5-fc3d-41b3-97a7-19d593489eb6 is already mounted on mountpath /var/data/kubelet/pods/0b3bd041-1272-40a4-96e2-76347e66205d/volumes/ibm~ibmc-block/pvc-7ef040e5-fc3d-41b3-97a7-19d593489eb6 "}
[root@oc4377604745 ~]# 

[root@oc4377604745 ~]# oc get pvc -n robot-shop
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
mongodb-volume-claim         Bound    pvc-6ec8e987-ad3c-4b21-966c-4a34310449f8   20Gi       RWO            ibmc-block-bronze   13m
mysql-data-volume-claim      Bound    pvc-aafa2ec1-f3ee-4092-9fb0-24c9e8278919   20Gi       RWO            ibmc-block-bronze   13m
mysql-scripts-volume-claim   Bound    pvc-7ef040e5-fc3d-41b3-97a7-19d593489eb6   20Gi       RWO            ibmc-block-bronze   13m
redis-volume-claim           Bound    pvc-e51dcd9d-cd58-422c-a4ca-37e7350f690c   20Gi       RWO            ibmc-block-bronze   13m
[root@oc4377604745 ~]# 

[root@oc4377604745 ~]# oc get sc ibmc-block-bronze -o yaml
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - dal12
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"allowedTopologies":[{"matchLabelExpressions":[{"key":"failure-domain.beta.kubernetes.io/zone","values":["dal12"]}]}],"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"creationTimestamp":"2020-10-06T09:02:20Z","labels":{"app":"ibmcloud-block-storage-plugin","chart":"ibmcloud-block-storage-plugin-1.7.1","heritage":"Helm","release":"release-name"},"name":"ibmc-block-bronze","resourceVersion":"36324224","selfLink":"/apis/storage.k8s.io/v1/storageclasses/ibmc-block-bronze","uid":"a4ae7357-9c3c-4d49-affd-7db0bc9ae0b8"},"parameters":{"billingType":"hourly","classVersion":"2","fsType":"ext4","iopsPerGB":"2","sizeRange":"[20-12000]Gi","type":"Endurance"},"provisioner":"ibm.io/ibmc-block","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2020-10-06T11:14:10Z"
  labels:
    app: ibmcloud-block-storage-plugin
    chart: ibmcloud-block-storage-plugin-1.7.1
    heritage: Helm
    release: release-name
  name: ibmc-block-bronze
  resourceVersion: "36386095"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/ibmc-block-bronze
  uid: 3d5a5165-b26f-44be-8133-40082d7073fc
parameters:
  billingType: hourly
  classVersion: "2"
  fsType: ext4
  iopsPerGB: "2"
  sizeRange: '[20-12000]Gi'
  type: Endurance
provisioner: ibm.io/ibmc-block
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

**Comment by ashoks27** [comment]
@pranavgaikwad Can you please advise here.. The both robot-shop and shock-shop applications are not working after migration . Also these applications are not working even if install them manually on the Target openshift 4.4 Cluster.

**Comment by jwmatthews** [comment]
@ashoks27 @pranavgaikwad I deployed on IBM ROKS with OCP 4.5 as a test. 

The immediate issue I see is if I deploy robot-shop none of the PVCs are bound in IBM ROKS.  I think this is because in our demo clusters we explicitly pre-create NFS PVs of no storageClass and intended to use robot shop to use NFS PVs.  In the IBM ROKS environment, there are no PVs of no storageClass, so when we deploy the app the PVCs are never bound.

I was able to resolve by removing the 'storageClass: ""' specifications
Example:  https://github.com/konveyor/mig-demo-apps/blob/master/apps/robot-shop/manifest.yaml#L209

Once I removed all the 'storageClasses: ""' then the PVCs were created.

My understanding is this is working 'as expected' for now as when we specify:  storageClass: ""'  it avoids using the 'default' storage class and uses PVs that exist with no storage class (hence matches the environment for our demos so NFS PVs are picked up).

Probably some cleanup we can do so this demo app can be used for multiple purposes, at moment I'd consider this a bit hard coded for our specific demo env for NFS.

@pranavgaikwad please correct me if I'm misunderstanding the issue.


There may be a second issue happening with the migration, I haven't been able to attempt a migration yet.  @ashoks27 I'd suggest looking at the storageclass you selected for the target when you created the MigPlan, perhaps you need to pick a different storageclass. 

For what it's worth, in my IBM ROKS cluster the default storageclass is 'ibmc-block-gold', I saw success deploying robot-shop with that storageclass.

**Comment by ashoks27** [comment]
Hi @jwmatthews ,

Thank a lot for your quick testing in IBM cloud and response.  I have tried again to deploy robot-shop with  storageclass as ibmc-block-gold' and also changed the apiVersion from apps/v1beta1 to apiVersion: apps/v1 as we got the below error. 

** **unable to recognize "manifest.yaml": no matches for kind "Deployment" in version "apps/v1beta1"** **

After creating the application with the updated manifest file , we got below Volume binding error in mysql deploy. 

[root@oc8660015353 robot-shop]# oc get pods -n robot-shop
NAME                         READY   STATUS    RESTARTS   AGE
cart-699567cb75-wcfxt        1/1     Running   0          47m
catalogue-7476fdc8f4-vs6hj   1/1     Running   0          47m
dispatch-85ff479cdd-znsmc    1/1     Running   0          47m
mongodb-59b795bd6b-qnk9j     1/1     Running   0          47m
**mysql-1-deploy               0/1     Error     0          47m**
payment-695779d6bb-ddhjs     1/1     Running   0          47m
rabbitmq-7b44f9c449-8s5cr    1/1     Running   0          47m
ratings-c45895c99-wxkn6      1/1     Running   0          47m
redis-78dd47d8c-kdc6p        1/1     Running   0          47m
shipping-6fbbc47b67-hzgnh    1/1     Running   1          47m
user-56987c97fd-mnp94        1/1     Running   0          47m
web-ffbbb68c7-qhmzc          1/1     Running   0          47m

Events 

<unknown>   Warning   FailedScheduling              pod/mysql-1-f85st                                  error while running "VolumeBinding" filter plugin for pod "mysql-1-f85st": pod has unbound immediate PersistentVolumeClaims
<unknown>   Warning   FailedScheduling              pod/mysql-1-f85st                                  error while running "VolumeBinding" filter plugin for pod "mysql-1-f85st": pod has unbound immediate PersistentVolumeClaims
<unknown>   Warning   FailedScheduling              pod/mysql-1-f85st                                  0/6 nodes are available: 6 node(s) had volume node affinity conflict.
<unknown>   Warning   FailedScheduling              pod/mysql-1-f85st                                  skip schedule deleting pod: robot-shop/mysql-1-f85st
<unknown>   Warning   FailedScheduling              pod/mysql-1-mbjw8                                  error while running "VolumeBinding" filter plugin for pod "mysql-1-mbjw8": pod has unbound immediate PersistentVolumeClaims
<unknown>   Warning   FailedScheduling              pod/mysql-1-mbjw8                                  0/6 nodes are available: 6 node(s) had volume node affinity conflict.

**Below listed are the steps we tried to troubleshoot further.**

We have updated the Zone details of "mysql-data-volume-claim " and "mysql-scripts-volume-claim" PVC to have disk assigned from the same zone . 

[root@oc4377604745 ~]# oc describe persistentvolumeclaim/mysql-data-volume-claim |grep -i zone
               zone=dal12
[root@oc4377604745 ~]# oc describe persistentvolumeclaim/mysql-scripts-volume-claim |grep -i zone
               zone=dal12
[root@oc4377604745 ~]# 

After changing the Zone informations , now we having the below error.

[root@oc4377604745 ~]# oc get pods,pvc
NAME                             READY   STATUS              RESTARTS   AGE
pod/cart-699567cb75-795d4        1/1     Running             0          39m
pod/catalogue-7476fdc8f4-vjvmd   1/1     Running             0          39m
pod/dispatch-85ff479cdd-c5bqx    1/1     Running             0          39m
pod/mongodb-59b795bd6b-n6k6k     1/1     Running             0          39m
pod/mysql-2-ccv95                2/2     Running             0          23m
pod/mysql-2-deploy               1/1     Running             0          23m
pod/mysql-2-hook-post            0/1     ContainerCreating   0          23m
pod/payment-695779d6bb-z6mrm     1/1     Running             0          39m
pod/rabbitmq-7b44f9c449-h2s79    1/1     Running             0          39m
pod/ratings-c45895c99-h8bjr      1/1     Running             0          39m
pod/redis-78dd47d8c-jpbzw        1/1     Running             0          39m
pod/shipping-6fbbc47b67-js5vr    1/1     Running             0          39m
pod/user-56987c97fd-c72qp        1/1     Running             0          39m
pod/web-ffbbb68c7-8h2vp          1/1     Running             0          39m

NAME                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
persistentvolumeclaim/mongodb-volume-claim         Bound    pvc-53afbbd5-36a4-47dd-9661-f854b340ee6b   20Gi       RWO            ibmc-block-gold   39m
persistentvolumeclaim/mysql-data-volume-claim      Bound    pvc-b2a46d2b-a504-4b1f-8d0c-3bd601d363dc   20Gi       RWO            ibmc-block-gold   26m
persistentvolumeclaim/mysql-scripts-volume-claim   Bound    pvc-2b286716-c96b-4812-be47-e9acf123bcdf   20Gi       RWO            ibmc-block-gold   26m
persistentvolumeclaim/redis-volume-claim           Bound    pvc-6ce3d572-e8f7-459a-824c-473381ec2cd4   20Gi       RWO            ibmc-block-gold   39m
[root@oc4377604745 ~]# 

[root@oc4377604745 ~]# oc describe po pod/mysql-2-hook-post
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'oc get resource/<resource_name>' instead of 'oc get resource resource/<resource_name>'
[root@oc4377604745 ~]# oc describe pod/mysql-2-hook-post
Name:               mysql-2-hook-post
Namespace:          robot-shop
Priority:           0
PriorityClassName:  <none>
Node:               10.74.175.171/10.74.175.171
Start Time:         Thu, 08 Oct 2020 14:58:35 +0530
Labels:             openshift.io/deployer-pod-for.name=mysql-2
                    openshift.io/deployer-pod.type=hook-post
Annotations:        openshift.io/deployment.name: mysql-2
                    openshift.io/scc: restricted
Status:             Pending
IP:                 
Containers:
  lifecycle:
    Container ID:  
    Image:         image-registry.openshift-image-registry.svc:5000/openshift/mysql@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      sleep 120 && zcat /tmp/mysql-init-scripts/10-dump.sql.gz | /opt/rh/rh-mysql57/root/bin/mysql --force -h $MYSQL_SERVICE_HOST -u root -pR00t@123 -D $MYSQL_DATABASE -P 3306 && /opt/rh/rh-mysql57/root/bin/mysql -h $MYSQL_SERVICE_HOST -u root -pR00t@123 -P 3306 < /tmp/mysql-init-scripts/20-ratings.sql && sleep 60
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  800Mi
    Requests:
      cpu:     100m
      memory:  400Mi
    Environment:
      MYSQL_PASSWORD:                  secret
      MYSQL_DATABASE:                  cities
      MYSQL_ROOT_PASSWORD:             R00t@123
      MYSQL_USER:                      shipping
      OPENSHIFT_DEPLOYMENT_NAME:       mysql-2
      OPENSHIFT_DEPLOYMENT_NAMESPACE:  robot-shop
    Mounts:
      /tmp/mysql-init-scripts from mysql-scripts-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-sfwlx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  mysql-scripts-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mysql-scripts-volume-claim
    ReadOnly:   false
  default-token-sfwlx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-sfwlx
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                  From                    Message
  ----     ------       ----                 ----                    -------
  Normal   Scheduled    <unknown>            default-scheduler       Successfully assigned robot-shop/mysql-2-hook-post to 10.74.175.171
  Warning  FailedMount  8m56s (x3 over 13m)  kubelet, 10.74.175.171  Unable to attach or mount volumes: unmounted volumes=[mysql-scripts-volume], unattached volumes=[default-token-sfwlx mysql-scripts-volume]: timed out waiting for the condition
  Warning  FailedMount  2m11s (x7 over 22m)  kubelet, 10.74.175.171  Unable to attach or mount volumes: unmounted volumes=[mysql-scripts-volume], unattached volumes=[mysql-scripts-volume default-token-sfwlx]: timed out waiting for the condition
[root@oc4377604745 ~]# 

Attached below is the updated Manifest file and logs for your quick reference. Please check and let me know if you need any further details. 

[manifest (1).txt](https://github.com/konveyor/mig-demo-apps/files/5346986/manifest.1.txt)
[logs_robot-shop.txt](https://github.com/konveyor/mig-demo-apps/files/5347037/logs_robot-shop.txt)

Thank you.

**Comment by jwmatthews** [comment]
Haven't had time to look more into this, but I did see '**volume node affinity**' mentioned, linking the below issue in controller that recently saw something similar with creating stage pods:

https://github.com/konveyor/mig-controller/issues/694

**Comment by pranavgaikwad** [comment]
@ashoks27 The root cause of this issue is same as I described here: https://github.com/konveyor/mig-controller/issues/694#issuecomment-706242906

The Post Hook of a Deployment is used to perform tasks as soon as deployment comes up. In the `robot-shop` app, we make use of the Post Hook to initiate the MySql database with sample entries. The Deployment launches a new _lifecycle_ pod to run the hook. This pod shares the volume with the original MySql pod and is scheduled on the same node as the MySql pod. This is where problem arises. 

I can definitely remove the post hook and move the database initialization logic in the `entrypoint.sh` script. It will let you deploy the app without the need of an additional Pod. Please let me know if you'd be interested in something like that.

**Comment by ashoks27** [comment]
@pranavgaikwad Thanks for your update. Yes it would be great if you could remove the post hook. It will be helpful for us to complete for testing on CAM.

**Comment by ashoks27** [comment]
@pranavgaikwad Now we are migrating the sock-shop apps in another OCP 4.5 cluster ( NOT ROKS ). The only issue we had was error Liveliness and readiness for most of the deployments and after increasing the delay time all deployments started except and user-db. The user-db deploy has the below errors. Could you please help to fix the below errors .Thanks

[root@ocp4-bastion ~]# oc get pods
NAME                           READY   STATUS             RESTARTS   AGE
carts-7886645b96-dksw9         1/1     Running            0          148m
carts-db-f8fcf9689-lqf2d       1/1     Running            0          162m
catalogue-6b6f7b7d55-kj7t6     1/1     Running            0          162m
catalogue-db-1-deploy          0/1     Completed          0          162m
catalogue-db-1-hook-post       0/1     Completed          0          162m
catalogue-db-1-wpbkj           1/1     Running            0          162m
front-end-7cf969755b-4mpln     1/1     Running            0          162m
orders-6cf79884b-hqfv5         1/1     Running            0          162m
orders-db-589c9c9f79-dmv8d     1/1     Running            0          162m
payment-685c84b67d-8gq59       1/1     Running            0          162m
queue-master-c8bc96c49-8ptnx   1/1     Running            1          162m
rabbitmq-586db49d59-xg44q      2/2     Running            0          162m
session-db-5f4bc9856d-db2bd    1/1     Running            0          162m
shipping-86b57b8bb5-drrtr      1/1     Running            0          136m
user-69b48cbd5b-srxbz          1/1     Running            0          19m
user-db-7fd59567b6-d42c5       0/1     CrashLoopBackOff   8          16m
[root@ocp4-bastion ~]#
[root@ocp4-bastion ~]#
[root@ocp4-bastion ~]# oc logs -f user-db-7fd59567b6-d42c5
2020-11-02T11:50:01.407+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db-users 64-bit host=user-db-7fd59567b6-d42c5
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten] db version v3.2.10
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten] git version: 79d9b3ab5ce20f51c272b4411202710a082d0317
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten] modules: none
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten] build environment:
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten]     distmod: debian81
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten]     distarch: x86_64
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2020-11-02T11:50:01.408+0000 I CONTROL  [initandlisten] options: { config: "/etc/mongodb.conf", storage: { dbPath: "/data/db-users", mmapv1: { smallFiles: true } } }
2020-11-02T11:50:01.413+0000 I -        [initandlisten] Detected data files in /data/db-users created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2020-11-02T11:50:01.414+0000 I STORAGE  [initandlisten] exception in initAndListen: 98 Unable to create/open lock file: /data/db-users/mongod.lock errno:13 Permission denied Is a mongod instance already running?, terminating
2020-11-02T11:50:01.415+0000 I CONTROL  [initandlisten] dbexit:  rc: 100
[root@ocp4-bastion ~]#

**Comment by pranavgaikwad** [comment]
@ashoks27 What was the storage class on destination? And, did you choose the Quiesce application option for migration?

**Comment by ashoks27** [comment]
@pranavgaikwad Its is NFS storgae class in both source and Target . Yes I did quiesce application option and all pods are scaled down to 0 in source. I have tried it today as well and most of the pods are showing error. It will be fixed if we increase the Liveliness and readiness time delay except the user-db pod. Please check and advise here.

Also The migration was completed with some warnings. "Migration succeeded with warnings. There were errors found in 2 Restic volume restores. See restore `7997df30-1de3-11eb-9f0d-251b8468cc74-qjddl` for details"

Attached below is the logs for your reference.

[root@ocp4-bastion ~]# oc get migplan -n openshift-migration
NAME    AGE
aacg    5d5h
sock1   38m
[root@ocp4-bastion ~]#
[root@ocp4-bastion ~]# oc describe migplan sock1
Error from server (NotFound): migplans.migration.openshift.io "sock1" not found
[root@ocp4-bastion ~]# oc describe migplan sock1 -n openshift-migration
Name:         sock1
Namespace:    openshift-migration
Labels:       <none>
Annotations:  openshift.io/touch: b5394539-1de7-11eb-b0f5-0a580a830076
API Version:  migration.openshift.io/v1alpha1
Kind:         MigPlan
Metadata:
  Creation Timestamp:  2020-11-03T14:39:15Z
  Generation:          5
  Managed Fields:
    API Version:  migration.openshift.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:destMigClusterRef:
          .:
          f:name:
          f:namespace:
        f:migStorageRef:
          .:
          f:name:
          f:namespace:
        f:namespaces:
        f:srcMigClusterRef:
          .:
          f:name:
          f:namespace:
    Manager:      Mozilla
    Operation:    Update
    Time:         2020-11-03T14:42:51Z
    API Version:  migration.openshift.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:openshift.io/touch:
      f:spec:
        f:persistentVolumes:
      f:status:
        .:
        f:conditions:
        f:excludedResources:
        f:observedDigest:
    Manager:         manager
    Operation:       Update
    Time:            2020-11-03T15:17:37Z
  Resource Version:  40823125
  Self Link:         /apis/migration.openshift.io/v1alpha1/namespaces/openshift-migration/migplans/sock1
  UID:               d0cd3e7f-8f21-4cb0-874c-0046bee8bbd2
Spec:
  Dest Mig Cluster Ref:
    Name:       host
    Namespace:  openshift-migration
  Mig Storage Ref:
    Name:       osv
    Namespace:  openshift-migration
  Namespaces:
    sock-shop
  Persistent Volumes:
    Capacity:  10Gi
    Name:      pvc-98554283-0c76-11eb-8731-005056917705
    Pvc:
      Access Modes:
        ReadWriteOnce
      Has Reference:  true
      Name:           carts-data-volume-claim
      Namespace:      sock-shop
    Selection:
      Action:         copy
      Copy Method:    filesystem
      Storage Class:  managed-nfs-storage
    Storage Class:    managed-nfs-storage
    Supported:
      Actions:
        copy
        move
      Copy Methods:
        filesystem
        snapshot
    Capacity:  10Gi
    Name:      pvc-98766d9b-0c76-11eb-8731-005056917705
    Pvc:
      Access Modes:
        ReadWriteOnce
      Has Reference:  true
      Name:           catalogue-data-volume-claim
      Namespace:      sock-shop
    Selection:
      Action:         copy
      Copy Method:    filesystem
      Storage Class:  managed-nfs-storage
    Storage Class:    managed-nfs-storage
    Supported:
      Actions:
        copy
        move
      Copy Methods:
        filesystem
        snapshot
    Capacity:  10Gi
    Name:      pvc-98b71bd3-0c76-11eb-8731-005056917705
    Pvc:
      Access Modes:
        ReadWriteOnce
      Has Reference:  true
      Name:           orders-data-volume-claim
      Namespace:      sock-shop
    Selection:
      Action:         copy
      Copy Method:    filesystem
      Storage Class:  managed-nfs-storage
    Storage Class:    managed-nfs-storage
    Supported:
      Actions:
        copy
        move
      Copy Methods:
        filesystem
        snapshot
    Capacity:  10Gi
    Name:      pvc-99177f18-0c76-11eb-8731-005056917705
    Pvc:
      Access Modes:
        ReadWriteOnce
      Has Reference:  true
      Name:           user-data-volume-claim
      Namespace:      sock-shop
    Selection:
      Action:         copy
      Copy Method:    filesystem
      Storage Class:  managed-nfs-storage
    Storage Class:    managed-nfs-storage
    Supported:
      Actions:
        copy
        move
      Copy Methods:
        filesystem
        snapshot
  Src Mig Cluster Ref:
    Name:       ocp3-11
    Namespace:  openshift-migration
Status:
  Conditions:
    Category:              Required
    Last Transition Time:  2020-11-03T14:39:37Z
    Message:               The `persistentVolumes` list has been updated with discovered PVs.
    Reason:                Done
    Status:                True
    Type:                  PvsDiscovered
    Category:              Required
    Last Transition Time:  2020-11-03T14:39:41Z
    Message:               The storage resources have been created.
    Status:                True
    Type:                  StorageEnsured
    Category:              Required
    Last Transition Time:  2020-11-03T14:39:46Z
    Message:               The migration registry resources have been created.
    Status:                True
    Type:                  RegistriesEnsured
    Category:              Required
    Last Transition Time:  2020-11-03T14:39:46Z
    Message:               The migration plan is ready.
    Status:                True
    Type:                  Ready
    Category:              Advisory
    Last Transition Time:  2020-11-03T14:48:20Z
    Message:               Limited validation; PV discovery and resource reconciliation suspended.
    Status:                True
    Type:                  Suspended
  Excluded Resources:
    imagetags
    templateinstances
    clusterserviceversions
    packagemanifests
    subscriptions
    servicebrokers
    servicebindings
    serviceclasses
    serviceinstances
    serviceplans
  Observed Digest:  f1ebb60da4c66f1a2f9235da3cb9be3e8539f592c61fe82619fe4d9aedbe5509
Events:             <none>


[root@ocp4-bastion ~]# oc get pods
NAME                           READY   STATUS             RESTARTS   AGE
carts-86d675b949-mrwcm         0/1     Running            4          27m
carts-db-f8fcf9689-m94kl       0/1     CrashLoopBackOff   10         27m
catalogue-6b6f7b7d55-jtlr8     0/1     Running            5          27m
catalogue-db-1-deploy          0/1     Error              0          27m
catalogue-db-1-hook-post       0/1     Error              0          27m
front-end-7cf969755b-6hdv8     1/1     Running            0          27m
orders-6cf79884b-7x5k5         0/1     Running            4          27m
orders-db-589c9c9f79-rqjfq     0/1     CrashLoopBackOff   10         27m
payment-685c84b67d-qvxnt       1/1     Running            0          27m
queue-master-c8bc96c49-q7z6d   1/1     Running            0          27m
rabbitmq-586db49d59-sdwwl      2/2     Running            0          27m
session-db-5f4bc9856d-78vw5    1/1     Running            0          27m
shipping-667fd59768-9khf2      0/1     Running            4          27m
user-547cf95f9d-x5qck          0/1     Running            5          27m
user-db-7fd59567b6-6kmkk       0/1     CrashLoopBackOff   10         27m
[root@ocp4-bastion ~]#
[root@ocp4-bastion ~]#
[root@ocp4-bastion ~]# oc get sc
NAME                   PROVISIONER                        RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
hostpath-provisioner   kubevirt.io/hostpath-provisioner   Delete          WaitForFirstConsumer   false                  55d
managed-nfs-storage    fuseim.pri/ifs                     Delete          Immediate              false                  4d6h
nfs (default)          kubernetes.io/no-provisioner       Delete          Immediate              false                  55d
[root@ocp4-bastion ~]#

**Comment by ashoks27** [comment]
@pranavgaikwad Do we have any update here. Thanks

**Comment by shawn-hurley** [comment]
cross-posting response here: 

https://github.com/konveyor/mig-controller/issues/694#issuecomment-722451850

@ashoks27
